from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from app.services.gesture_detection import detect_landmark_sign as detect_sign
from app.services.sentence_builder import clear_sentence, update_sentence
from app.services.tts_service import speak

router = APIRouter()

LETTER_TO_WORD = {
    "A": "Hello 👋",
    "B": "Good Morning 🌅",
    "C": "Good Evening 🌇",
    "D": "How are you? 🙂",
    "E": "I am fine 👍",
    "F": "Thank You 🙏",
    "G": "Sorry 😔",
    "H": "Please 🙏",
    "I": "Yes 👍",
    "J": "No ❌",
    "K": "Good Job 👏",
    "L": "All the Best 🎯"
}

@router.post("/detect")
async def detect(file: UploadFile = File(...)):
    image_bytes = await file.read()
    if not image_bytes:
        raise HTTPException(status_code=400, detail="Empty image received")

    sign, confidence = detect_sign(image_bytes)
    sentence = update_sentence(sign)

    text = LETTER_TO_WORD.get(str(sign).upper(), "") 

    return {
        "sign": sign,
        "text": text,
        "confidence": round(float(confidence), 2),
        "sentence": sentence
    }


@router.post("/practice-check")
async def practice(file: UploadFile = File(...), target: str = Form(...)):
    image_bytes = await file.read()
    
    sign, confidence = detect_sign(image_bytes)
    
    text = LETTER_TO_WORD.get(str(sign).upper(), "")

    return {
    "detected": sign,
    "text": text, 
    "target": target,
    "correct": str(sign).strip().upper() == str(target).strip().upper(),
    "confidence": round(float(confidence), 2)
}

@router.post("/speak")
async def text_to_speech(text: str):
    """
    Expects /speak?text=hello
    Returns the filename generated by gTTS
    """
    if not text.strip():
        return {"audio": None, "error": "No text provided"}

    audio_file = speak(text)
    
    # We return the filename; the frontend will play it via /static/{audio_file}
    return {"audio": audio_file}

@router.post("/clear-sentence")
def clear():
    clear_sentence()
    return {"message": "Sentence cleared", "sentence": ""}