from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from app.services.gesture_detection import detect_sign
from app.services.sentence_builder import clear_sentence, update_sentence
from app.services.tts_service import speak

router = APIRouter()

@router.post("/detect")
async def detect(file: UploadFile = File(...)):
    # 1. Read image bytes
    image_bytes = await file.read()
    if not image_bytes:
        raise HTTPException(status_code=400, detail="Empty image received")

    # 2. Inference: Get the character and confidence score
    sign, confidence = detect_sign(image_bytes)
    
    # 3. State Management: Append to the current running sentence
    sentence = update_sentence(sign)
    
    return {
        "sign": sign, 
        "confidence": round(float(confidence), 2), 
        "sentence": sentence
    }

@router.post("/practice-check")
async def practice(file: UploadFile = File(...), target: str = Form(...)):
    image_bytes = await file.read()
    
    # Check what the user is actually doing vs what they should be doing
    sign, confidence = detect_sign(image_bytes)
    
    return {
        "detected": sign,
        "target": target,
        "correct": str(sign).strip().upper() == str(target).strip().upper(),
        "confidence": round(float(confidence), 2)
    }

@router.post("/speak")
async def text_to_speech(text: str):
    """
    Expects /speak?text=hello
    Returns the filename generated by gTTS
    """
    if not text.strip():
        return {"audio": None, "error": "No text provided"}

    audio_file = speak(text)
    
    # We return the filename; the frontend will play it via /static/{audio_file}
    return {"audio": audio_file}

@router.post("/clear-sentence")
def clear():
    clear_sentence()
    return {"message": "Sentence cleared", "sentence": ""}